### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by Frozen** [asynkron/protoactor-go#195]
kot@MacBook-Pro-Konstantin.local:/Users/kot/projects/go/src/github.com/AsynkronIT/protoactor-go$ go test `go list ./... | grep -v consul`
```

--- FAIL: TestJsonSerializer_Serialize_PID_raw (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
	panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 7 [running]:
testing.tRunner.func1(0xc4201641e0)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x148c360, 0x15a6410)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
reflect.valueInterface(0x14c9640, 0xc4200114d0, 0x1b4, 0x14c9601, 0xc4200114d0, 0x1b4)
	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:942 +0x1dd
reflect.Value.Interface(0x14c9640, 0xc4200114d0, 0x1b4, 0x14c9640, 0xc4200114d0)
	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:931 +0x44
github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalValue(0xc420057f78, 0xc420057e98, 0xc4200b14a0, 0x1471680, 0xc420162560, 0x1b6, 0x0, 0x0, 0x1548372, 0x1)
	/Users/kot/projects/go/src/github.com/gogo/protobuf/jsonpb/jsonpb.go:423 +0xad
github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalField(0xc420057f78, 0xc420057e98, 0xc4200b14a0, 0x1471680, 0xc420162560, 0x1b6, 0x0, 0x0, 0x20, 0xc420016990)
	/Users/kot/projects/go/src/github.com/gogo/protobuf/jsonpb/jsonpb.go:383 +0x10b
github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalObject(0xc420057f78, 0xc420057e98, 0x17cb500, 0xc420162540, 0x0, 0x0, 0x0, 0x0, 0xc4200346b8, 0x1012ce8)
	/Users/kot/projects/go/src/github.com/gogo/protobuf/jsonpb/jsonpb.go:242 +0x527
github.com/gogo/protobuf/jsonpb.(*Marshaler).Marshal(0xc420034778, 0x17c4ec0, 0xc4200b2d20, 0x17cb500, 0xc420162540, 0xc420162540, 0x0)
	/Users/kot/projects/go/src/github.com/gogo/protobuf/jsonpb/jsonpb.go:79 +0xc1
github.com/gogo/protobuf/jsonpb.(*Marshaler).MarshalToString(0xc420034778, 0x17cb500, 0xc420162540, 0xc420162540, 0x0, 0x0, 0x2b3)
	/Users/kot/projects/go/src/github.com/gogo/protobuf/jsonpb/jsonpb.go:85 +0x6e
github.com/AsynkronIT/protoactor-go/remote.TestJsonSerializer_Serialize_PID_raw(0xc4201641e0)
	/Users/kot/projects/go/src/github.com/AsynkronIT/protoactor-go/remote/serializer_test.go:30 +0xa4
testing.tRunner(0xc4201641e0, 0x156b700)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:789 +0x2de
FAIL	github.com/AsynkronIT/protoactor-go/remote	0.015s
--- FAIL: TestRouterSendsUserMessageToChild (0.00s)
panic: interface conversion: interface {} is *router.mockProcess, not mock.Mock [recovered]
	panic: interface conversion: interface {} is *router.mockProcess, not mock.Mock

goroutine 6 [running]:
testing.tRunner.func1(0xc4201120f0)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x13b46a0, 0xc420060b00)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/stretchr/testify/mock.AssertExpectationsForObjects(0x1613580, 0xc4201120f0, 0xc420057f78, 0x2, 0x2, 0x0)
	/Users/kot/projects/go/src/github.com/stretchr/testify/mock/mock.go:351 +0x1b4
github.com/AsynkronIT/protoactor-go/router.TestRouterSendsUserMessageToChild(0xc4201120f0)
	/Users/kot/projects/go/src/github.com/AsynkronIT/protoactor-go/router/process_test.go:35 +0x580
testing.tRunner(0xc4201120f0, 0x1438e30)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:789 +0x2de

```

go version go1.9.2 darwin/amd64

is it ok?

**Comment by vito-c** [comment]
Even with the failed tests I was able to get the hello world app up and running

**Comment by PotterDai** [comment]
@rogeralsing This might due to the fact that I accidentally removed json:"-" in this line
https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/pid.go#L16
This is purely due to a warning reporting from go lint check.
I think I should revert it back.

**Comment by PotterDai** [comment]
It seems I did this commit after this issue. So those two should be unrelated. Nevermind = ) 
@rogeralsing 
https://github.com/AsynkronIT/protoactor-go/commit/5f989b34331e8e6a9f0ef5f15d4344cccbf5dab4
